

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/job # 调度器访问地址
    executor:
      appname: blog-job
      #对应在xxl-job控制条新增执行器时，填写的APPNAME，执行器心跳注册分组依据
      ip:
      #执行器IP默认为空表示自动获取ip，
      port: 9998
      # 执行器的默认端口为9999，port是一个内置的jetty服务端口
      logpath: /xxl-job/jobhandler
      # 执行器运行日志文件存储的磁盘位置，需要对该路径拥有读写权限
      logretentiondays: -1
    accessToken:
server:
  port: 8081
---
spring:
  application:
    name: xxl-job
  boot:
    admin:
      client:
        url: http://localhost:8082
management:
  endpoints:
    web:
      exposure:
        include: "*"